/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passwordvault;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jilbert PC
 */
public class EditAccountSection extends javax.swing.JFrame {
    public String loginusername;
    public String loginpassword;
    public String logintable;
    public int id = 0;
    public String accsaname = "";
    public String accusername = "";
    public String accemail = "";
    public String password = "";
    public String accaddinfo = "";
    /**
     * Creates new form AddPasswordSection
     */
    public EditAccountSection() {
        initComponents();
        this.setResizable(false);
        setIcon();
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("padlock (1).png")));
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        editsaname = new javax.swing.JTextField();
        editusername = new javax.swing.JTextField();
        editgmail = new javax.swing.JTextField();
        editpassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        accountsbutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        editaddinfo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        label2.setText("USERNAME:");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, 32));

        label3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        label3.setText("GMAIL: *");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, 32));

        label4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        label4.setText("PASSWORD: *");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, 30));

        label1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        label1.setText("SITE/APP NAME: *");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, 32));

        label5.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        label5.setText("ADDITIONAL INFO:");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, 32));

        jLabel2.setFont(new java.awt.Font("Perpetua", 1, 38)); // NOI18N
        jLabel2.setText("EDIT ACCOUNT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/padlock.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, 70));

        editsaname.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        editsaname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(editsaname, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 270, 30));

        editusername.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        editusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(editusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 270, 30));

        editgmail.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        editgmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(editgmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 270, 30));

        editpassword.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        editpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(editpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 270, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/facebook.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/instagram.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/twitter.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/yahoo.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/tiktok.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/snapchat.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/email.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/telegram.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/linkedin.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 300, -1, -1));

        accountsbutton.setBackground(new java.awt.Color(234, 234, 234));
        accountsbutton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        accountsbutton.setText("ACCOUNTS");
        accountsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(accountsbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 120, -1));

        logoutbutton.setBackground(new java.awt.Color(234, 234, 234));
        logoutbutton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        logoutbutton.setText("LOGOUT");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 120, -1));

        save.setBackground(new java.awt.Color(234, 234, 234));
        save.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/diskette.png"))); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, -1, -1));

        editaddinfo.setColumns(20);
        editaddinfo.setRows(5);
        jScrollPane1.setViewportView(editaddinfo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 270, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/pexels-pixabay-274895 (3).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 704));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String savesaname = editsaname.getText();
        String saveusername = editusername.getText();
        String savegmail = editgmail.getText();
        String savepassword = editpassword.getText();
        String saveaddinfo = editaddinfo.getText();
        
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");  
        SimpleDateFormat formatter2 = new SimpleDateFormat("HH:mm"); 
        Date datenow = new Date(); 
        
        String dbName = "Vault";
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+dbName, "root", "root");
            String sql = "UPDATE " + logintable + " SET saname = ?, username = ?, gmail = ?, password = ?, addinfo = ?, date = ? where id = ?";
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setString(1, savesaname);
            ps.setString(2, saveusername);
            ps.setString(3, savegmail);
            ps.setString(4, savepassword);
            ps.setString(5, saveaddinfo);
            ps.setString(6, formatter.format(datenow));
            ps.setInt(7, id);
            ps.execute();

            JOptionPane.showMessageDialog(this, "Edit Account Successful.", "Successful", JOptionPane.PLAIN_MESSAGE);

            String typeof = "EDIT";
            String history0 = logintable + "history";

            String sql2 = "INSERT into " +  history0 + "(saname, username, gmail, password, addinfo, typeof, date, time) VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps2 = con.prepareStatement(sql2);

            ps2.setString(1, savesaname);
            ps2.setString(2, saveusername);
            ps2.setString(3, savegmail);
            ps2.setString(4, savepassword);
            ps2.setString(5, saveaddinfo);
            ps2.setString(6, typeof);
            ps2.setString(7, formatter.format(datenow));
            ps2.setString(8, formatter2.format(datenow));
            ps2.execute();

        }
        catch (SQLException ex) {
            Logger.getLogger(EditAccountSection.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_saveActionPerformed

    private void accountsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsbuttonActionPerformed
        VaultSection VS = new VaultSection();
        VS.loginusername = loginusername;
        VS.loginpassword = loginpassword;
        VS.logintable = logintable;
        VS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountsbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        LoginSection LS = new LoginSection();
        LS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAccountSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAccountSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAccountSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAccountSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAccountSection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountsbutton;
    public javax.swing.JTextArea editaddinfo;
    public javax.swing.JTextField editgmail;
    public javax.swing.JTextField editpassword;
    public javax.swing.JTextField editsaname;
    public javax.swing.JTextField editusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
