/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passwordvault;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jilbert PC
 */
public class LoginSection extends javax.swing.JFrame {
    public String loginusername;
    public String loginpassword;
    /**
     * Creates new form LoginSection
     */
    public LoginSection() {
        initComponents();
        password.setEchoChar('*');
        this.setResizable(false);
        setIcon();
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("padlock (1).png")));
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        label2.setText("USERNAME:");
        jPanel2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, 32));

        label3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        label3.setText("PASSWORD:");
        jPanel2.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, 32));

        username.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        username.setForeground(new java.awt.Color(102, 102, 102));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 160, 20));

        login.setBackground(new java.awt.Color(204, 204, 204));
        login.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/user.png"))); // NOI18N
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 260, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/login.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        password.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        password.setForeground(new java.awt.Color(102, 102, 102));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/pexels-karina-zhukovskaya-6446708 (2).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -480, 670, 890));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        try {
            String uname = username.getText();
            String pass = password.getText();
            
            String dbName = "Vault";
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+dbName, "root", "root");
                Statement st = con.createStatement();
                
                String exe = "select * from admins";

                boolean flag = false;
                boolean tempflag = true;
                ResultSet rs = st.executeQuery(exe);
                while (rs.next()) {
                    String data1 = rs.getString("username");
                    String data2 = rs.getString("password");
                    
                    if (data1.equals(uname) && data2.equals(pass)) {
                        SignUpSection SUS = new SignUpSection();
                        SUS.setVisible(true);
                        tempflag = false;
                        this.dispose();
                        break;
                    }
                }
                
                String tablename = "";
                
                if (tempflag) {
                    String exe2 = "select * from Users";

                    ResultSet rs2 = st.executeQuery(exe2);
                    while (rs2.next()) {
                        String data1 = rs2.getString("username");
                        String data2 = rs2.getString("password");

                        if (data1.equals(uname) && data2.equals(pass)) {
                            tablename = rs2.getString("tablename");
                            flag = true;
                            break;
                        }
                    }

                    if (flag) {
                        AddPasswordSection APS = new AddPasswordSection();
                        APS.loginusername = uname;
                        APS.loginpassword = pass;
                        APS.logintable = tablename;
                        APS.setVisible(true);

                        this.dispose();
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "No account existed.", "Error", JOptionPane.ERROR_MESSAGE);
                        username.setText("");
                        password.setText("");
                    }
                }
            }
            catch (SQLException ex) {
                    Logger.getLogger(LoginSection.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please fill out all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
