/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passwordvault;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jilbert PC
 */
public class SignUpSection extends javax.swing.JFrame {

    /**
     * Creates new form LoginSection
     */
    public SignUpSection() {
        initComponents();
        this.setResizable(false);
        setIcon();
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("padlock (1).png")));
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        logout = new javax.swing.JButton();
        register = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        label1.setText("NAME:");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 32));

        label2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        label2.setText("USERNAME:");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 32));

        label3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        label3.setText("PASSWORD:");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 32));

        lastname.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        lastname.setForeground(new java.awt.Color(102, 102, 102));
        lastname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastname.setText("LASTNAME");
        lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameFocusGained(evt);
            }
        });
        jPanel1.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 130, 30));

        username.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(102, 102, 102));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 270, 30));

        firstname.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        firstname.setForeground(new java.awt.Color(102, 102, 102));
        firstname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstname.setText("FIRSTNAME");
        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameFocusGained(evt);
            }
        });
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 130, 30));

        logout.setBackground(new java.awt.Color(204, 204, 204));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/logout.png"))); // NOI18N
        logout.setText("LOUGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        register.setBackground(new java.awt.Color(204, 204, 204));
        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/user.png"))); // NOI18N
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        password.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 242, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/pexels-frederic-bartl-786123.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-420, -300, 1030, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        try {
            String fname = firstname.getText();
            String lname = lastname.getText();
            String uname = username.getText();
            String pass = password.getText();
            String tname = fname + "table";
            String htname = fname + "tablehistory";
            
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");  
            Date datenow = new Date(); 
            
            String dbName = "Vault";
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+dbName, "root", "root");
                Statement st = con.createStatement();
                
                String sql = "INSERT into Users (firstname, lastname, username, password, tablename, dates) VALUES(?, ?, ?, ?, ?, ?)";
                PreparedStatement ps = con.prepareStatement(sql);

                ps.setString(1, fname);
                ps.setString(2, lname);
                ps.setString(3, uname);
                ps.setString(4, pass);
                ps.setString(5, tname);
                ps.setString(6, formatter.format(datenow));
                ps.execute();
                
                try {
                    String execute = "Create TABLE " + tname + "(id int not null auto_increment, SAName varchar(100), Username varchar(100), Gmail varchar(100), Password varchar(100), AddInfo varchar(255), Date varchar(50), time varchar(50), primary key (id))";
                    st.executeUpdate(execute);
                    
                    String execute2 = "Create TABLE " + htname + "(id int not null auto_increment, SAName varchar(100), Username varchar(100), Gmail varchar(100), Password varchar(100), AddInfo varchar(255), typeof varchar(50), Date varchar(50), time varchar(50), primary key (id))";
                    st.executeUpdate(execute2);
                    
                    JOptionPane.showMessageDialog(this, "Sign Up Successful", "Successful", JOptionPane.PLAIN_MESSAGE);
                }
                catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Account Already Exist.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch (SQLException ex) {
                    Logger.getLogger(SignUpSection.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please fill out all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registerActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        LoginSection LS = new LoginSection();
        LS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusGained
        firstname.setText("");
    }//GEN-LAST:event_firstnameFocusGained

    private void lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusGained
        lastname.setText("");
    }//GEN-LAST:event_lastnameFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpSection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton logout;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton register;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
